version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: burak
      POSTGRES_PASSWORD: burak123
      POSTGRES_DB: notes_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: notes_db
      DB_USER: burak
      DB_PASSWORD: burak123
    depends_on:
      - db

volumes:
  postgres-data:
