name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Repo’yu klonla
        uses: actions/checkout@v3

      - name: Docker’a login ol
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image’ı build et
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/not-defteri-api .

      - name: DockerHub’a push et
        run: docker push ${{ secrets.DOCKER_USERNAME }}/not-defteri-api
